import uuid from "react-uuid";
export const f2l = [
  {
    tipo: "f2l",
    caso: 1,
    algoritmo: "R' F R F'",
    imagen: f2l1,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 2,
    algoritmo: "y U' L' U L",
    imagen: f2l2,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 3,
    algoritmo: "y L' U' L",
    imagen: f2l3,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 4,
    algoritmo: "R U R'",
    imagen: f2l4,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 5,
    algoritmo: "U' R U R' U2 R U' R'",
    imagen: f2l5,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 6,
    algoritmo: "d R' U' R U2 R' U R",
    imagen: f2l6,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 7,
    algoritmo: "U' R U2 R' U2 R U' R'",
    imagen: f2l7,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 8,
    algoritmo: "d R' U2 R U2 R' U R",
    imagen: f2l8,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 9,
    algoritmo: "U' R U' R' U F' U' F",
    imagen: f2l9,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 10,
    algoritmo: "U' R U R' U R U R'",
    imagen: f2l10,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 11,
    algoritmo: "U' R U2 R' U F' U' F",
    imagen: f2l11,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 12,
    algoritmo: "R U' R' U R U' R' U2 R U' R'",
    imagen: f2l12,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 13,
    algoritmo: "y' U R' U R U' R' U' R",
    imagen: f2l13,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 14,
    algoritmo: "U' R U' R' U R U R'",
    imagen: f2l14,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 15,
    algoritmo: "R U R' U2 R U' R' U R U' R'",
    imagen: f2l15,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 16,
    algoritmo: "R U' R' U2 F' U' F",
    imagen: f2l16,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 17,
    algoritmo: "R U2 R' U' R U R'",
    imagen: f2l17,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 18,
    algoritmo: "y' R' U2 R U R' U' R",
    imagen: f2l18,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 19,
    algoritmo: "U R U2 R' U R U' R'",
    imagen: f2l19,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 20,
    algoritmo: "y' U' R' U2 R U' R' U R",
    imagen: f2l20,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 21,
    algoritmo: "U2 R U R' U R U' R'",
    imagen: f2l21,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 22,
    algoritmo: "F' L' U2 L F",
    imagen: f2l22,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 23,
    algoritmo: "R U R' U2 R U R' U' R U R'",
    imagen: f2l23,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 24,
    algoritmo: "F U R U' R' F' R U' R'",
    imagen: f2l24,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 25,
    algoritmo: "R' F' R U R U' R' F",
    imagen: f2l25,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 26,
    algoritmo: "U R U' R' U' F' U F",
    imagen: f2l26,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 27,
    algoritmo: "R U' R' U R U' R'",
    imagen: f2l27,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 28,
    algoritmo: "R U R' U' F R' F' R",
    imagen: f2l28,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 29,
    algoritmo: "R' F R F' R' F R F'",
    imagen: f2l29,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 30,
    algoritmo: "R U R' U' R U R'",
    imagen: f2l30,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 31,
    algoritmo: "U' R' F R F' R U' R'",
    imagen: f2l31,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 32,
    algoritmo: "R U R' U' R U R' U' R U R'",
    imagen: f2l32,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 33,
    algoritmo: "U' R U' R' U2 R U' R'",
    imagen: f2l33,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 34,
    algoritmo: "U R U R' U2 R U R'",
    imagen: f2l34,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 35,
    algoritmo: "U' R U R' U F' U' F",
    imagen: f2l35,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 36,
    algoritmo: "U2 R' F R F' U2 R U R'",
    imagen: f2l36,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 37,
    algoritmo: "R2 U2 F R2 F' U2 R' U R'",
    imagen: f2l37,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 38,
    algoritmo: "R U R' U' R U2 R' U' R U R'",
    imagen: f2l38,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 39,
    algoritmo: "R U R' U2 R U' R' U R U R'",
    imagen: f2l39,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 40,
    algoritmo: "R U' R' F R U R' U' F' R U' R'",
    imagen: f2l40,
    id: uuid(),
  },
  {
    tipo: "f2l",
    caso: 41,
    algoritmo: "R U R' U' R U' R' U2 y' R' U' R",
    imagen: f2l41,
    id: uuid(),
  },
  {
    tipo: "pll",
    caso: "Aa",
    algoritmo: "l' U R' D2 R U' R' D2 R2",
    imagen: pllAa,
    id: uuid(),
  },
];
